/*
 * This source file was generated by the Gradle 'init' task
 */
package tictactoe;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        // Test removed as App.java is a GUI entry point with no logic to unit test
    }
}
